// 앱은 여기서 타입만 가져간다. 쿼리는 /web·/admin의 serverId를 받는 함수로만 한다.
export type {
  Profile,
  NewProfile,
  Game,
  NewGame,
  Participant,
  NewParticipant,
  Availability,
  NewAvailability,
  ProfileMemo,
  SessionReview,
  UserBadge,
  Server,
  ServerMember,
  ProfileKeyword,
  AvailabilityInterval,
  ProfileLink,
  CertShot,
  AuditState,
  Rulebook,
  RulebookKind,
  CertApplication,
  AuditLogEntry,
  NotificationRecord,
} from "./schema";
