// 같은 글자는 어느 화면에서든 같은 색으로 보인다(시안 kit.jsx STATUS). 표에 없는 글자는 화면이 넘긴 색을 쓴다.
// primary 진행·선택 / warning 대기·주의 / danger 위반·제한 / success 완료 / gray 분류·메타
export const STATUS_TONE: Readonly<Record<string, StatusTone>> = {
  차단됨: "danger",
  추방: "danger",
  "봇 연결 끊김": "danger",
  "확인 실패": "danger",
  "이탈 처리됨": "warning",
  "디스코드 차단 실패": "warning",
  탈퇴: "gray",
  재가입: "gray",
  통과: "success",
  "모집 중": "primary",
  "사용 중": "primary",
  신규: "primary",
  나: "primary",
  소유자: "primary",
  "이 책": "primary",
  "숨긴 뒤 수정됨": "primary",
  "심사 대기": "warning",
  "숨김 중": "warning",
  미신청: "warning",
  중복: "warning",
  보류: "warning",
  사용: "warning",
  "스포일러 포함": "gray",
  "일정 조율 중": "warning",
  "제재 중": "danger",
  제재: "danger",
  "제재 30일": "danger",
  불참: "danger",
  "문제 지정": "danger",
  반려: "danger",
  반려됨: "danger",
  "운영진이 숨김": "danger",
  정상: "gray",
  "활동 가능": "success",
  확정: "success",
  유효: "gray",
  취소됨: "gray",
  "불참 취소됨": "gray",
  종료: "gray",
  비활성: "gray",
  운영진: "gray",
  참여: "gray",
  GM: "gray",
  "부적절한 표현": "gray",
  스포일러: "gray",
  욕설·비방: "gray",
  "개인정보 노출": "gray",
  "스포일러 미표시": "gray",
  "부적절한 이미지": "gray",
  "세션과 무관한 내용": "gray",
  기타: "gray",
};

export type StatusTone = "primary" | "warning" | "danger" | "success" | "gray";
